# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go  
        uses: actions/setup-go@v4  
        with:
          go-version: '1.22'

      - name: Cache Go modules  
        uses: actions/cache@v3  
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install golangci-lint  
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Tidy and verify modules  
        run: go mod tidy

      - name: Vet  
        run: go vet ./...

      - name: Lint  
        run: golangci-lint run

      - name: Test  
        run: go test ./... -coverprofile=coverage.out

      - name: Upload coverage  
        uses: actions/upload-artifact@v3  
        with:
          name: coverage-report
          path: coverage.out
